name: Convert STEP to PNG

on:
  workflow_dispatch:

jobs:
  f3d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install f3d
        run: |
          sudo apt install libopengl0 -y
          wget -O f3d.tar.gz https://github.com/f3d-app/f3d/releases/download/v2.3.0/F3D-2.3.0-Linux-x86_64.tar.gz
          mkdir f3d
          tar -xzf f3d.tar.gz -C f3d --strip-components=1

      - name: Generate .png
        run: |
          # ./f3d/bin/f3d "./docs/DCDC-FusePCB.step" --output "docs/DCDC-FusePCB.png"
          ./f3d/bin/f3d "./docs/DCDC-FusePCB.step"

      - name: Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory '*'
          git add .
          git commit -m "Updated PCB .png"
          git push
          
