# This is a basic workflow to help you get started with Actions
name: Install KiCAD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Export:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Cache KiCAD Install
      uses: actions/cache@v4
      id: cache-kicad
      with:
          path: "kicad"
          key: "7.0"

    - name: Install Kicad
      env:
        CACHE_HIT: ${{steps.cache-kicad.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --verbose --force --recursive kicad/* /
        else  
          sudo add-apt-repository ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install kicad
          mkdir -p kicad
          sudo dpkg -L kicad | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory kicad/
        fi
        
    - name: View Dir
      run: |
        dpkg -L kicad
