name: KiCAD STEP Export

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    kicad-docker:
      runs-on: ubuntu-latest
      container:
        image: kicad/kicad:7.0
        options: --user root
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Enumerate files
          id: file_lists
          run: |
            echo "PCB_FILES=$(find . -type f -name "*.kicad_pcb" -print)" >> "$GITHUB_OUTPUT"
            echo "SCH_FILES=$(find . -type f -name "*.kicad_sch" -print)" >> "$GITHUB_OUTPUT"

        - name: print
          env:
            PCB_FILES: ${{ steps.file_lists.PCB_FILES }}
          run: |
            echo "$PCB_FILES"
        
    
        
