name: Auto KiCAD Export

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    kicad-docker:
      if: ${{ github.actor != 'github-actions[bot]' }}
      
      runs-on: ubuntu-latest
      
      container:
        image: kicad/kicad:7.0
        options: --user root
        
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Clone Submodule
          run: git clone https://github.com/lhr-solar/UTSVT-KiCadLibraries.git

        - name: Checkout Submodule Branch
          run: |
            cd UTSVT-KiCadLibraries
            git checkout DCDC-FusePCB
            cd ..
        
        - name: Make docs directory
        - run: |
            if [ ! -d "$DIR" ]; then
              mkdir "$DIR"
            fi
            
            
        - name: Process PCB Files
          run: |
            for i in *.kicad_pcb; do
              [ -f "$i" ] || break
              BASE_NAME="$(echo $i | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1)"
              kicad-cli pcb export step --subst-models -o "docs/$BASE_NAME.step" "$i"
            done
            
        - name: Process SCH Files
          run: |
            for i in *.kicad_sch; do
              [ -f "$i" ] || break
              echo "$i"
            done
            
        - name: Push Changes
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global --add safe.directory '*'
            git add .
            git commit -m "Updated Exports"
            git push
            
    
        
