name: KiCAD STEP Export

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    kicad-docker:
      runs-on: ubuntu-latest
      container:
        image: kicad/kicad:7.0
        options: --user root
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Clone Submodule
          run: git clone https://github.com/lhr-solar/UTSVT-KiCadLibraries.git

        - name: Checkout Submodule Branch
          run: |
            cd UTSVT-KiCadLibraries
            git checkout DCDC-FusePCB
            cd ..

        - name: Process PCB Files
          run: |
            find . -type f -name "*.kicad_pcb" -print | while read -d $'\0' file
            do
                kicad-cli -h
            done
            
        - name: Process SCH Files
          run: |
            find . -type f -name "*.kicad_sch" -print | while read -d $'\0' file
            do
                kicad-cli -h
            done
        
