name: KiCAD STEP Export

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    kicad-docker:
      runs-on: ubuntu-latest
      container:
        image: kicad/kicad:7.0
        options: --user root
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Enumerate files
          id: file_lists
          run: |
            PCB_FILES=()
            while IFS= read -r -d '' file; do
              PCB_FILES+=("$file")
            done < <(find . -type f -name "*.kicad_pcb" -print0)
            echo "::set-output name=pcb_files::${PCB_FILES[*]}"
            echo "PCB_FILES=$(find . -type f -name "*.kicad_pcb" -print)" >> "$GITHUB_OUTPUT"

        - name: print
          env:
            PCB_FILES: ${{ steps.file_lists.outputs.PCB_FILES }}
            SCH_FILES: ${{ steps.file_lists.outputs.SCH_FILES }}
          run: |
            echo "$PCB_FILES"
            echo "$SCH_FILES"
        
    
        
