# This is a basic workflow to help you get started with Actions
name: KiCAD STEP Export

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gen_STEP:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone Submodule
      run: git clone https://github.com/lhr-solar/UTSVT-KiCadLibraries.git

    - name: Checkout DCDC-FusePCB Branch
      run: |
        cd UTSVT-KiCadLibraries
        git checkout DCDC-FusePCB
        cd ..

    - name: List Files in Submodule
      run: |
        echo "Contents of the submodule directory:"
        ls -la UTSVT-KiCadLibraries/UTSVT_Passive.pretty

    - name: Install Kicad
      uses: actions-for-kicad/setup-kicad@v1.0
      with:
        version: '7.0'

    - name: Generate STEP
      uses: actions-for-kicad/generate-kicad-files@v1.0
      with:
        file: './DCDC-FusePCB.kicad_pcb'
        type: 'pcb_step'

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'DCDC-FusePCB.step'
        path: './DCDC-FusePCB.step'
