# This is a basic workflow to help you get started with Actions
name: KiCAD STEP Export

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gen_STEP:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Clone Additional Repository
      run: git clone https://github.com/lhr-solar/UTSVT-KiCadLibraries.git temp_repo

    - name: List Files in Additional Repository
      run: |
        echo "Contents of the cloned repository:"
        ls -la temp_repo
